### ISSUE TITLE
Using style guides to improve code quality

### ISSUE THREAD

**Issue by zannain** [utsav0709/Tea-Cozy#2]
When developing a website or an application it is good practice to consult a style guide. This ensures consistency and shows that you are writing code that adheres to best practices for a particular language. A popular style guide is [Google's HTML/CSS Style Guide](https://google.github.io/styleguide/htmlcssguide.html#Type_Selectors) and you will notice that it does not recommend using elements and id selectors in conjunction. 

```css
/* style.css */
.downtown span,h3,.eastbay span,h3,.oakdale span,h3 {
  display: block;
  margin: 30px;
}
```

In this scenario a better approach would be to give the `<span>` a class name that is common among the nested child of `.downtown`, `.eastbay`, and `.oakdale`.
